server:
  port: 8082
spring:
  rabbitmq:
    request:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      producer: ex.producer.aula-spring
    routing-key:
      producer: rk.producer.aula-spring
    deadletter:
      producer: dt.producer.aula-spring